apiVersion: v1
kind: Service
metadata:
  name: agent-gke-demo
  labels:
    app: agent-gke-demo
spec:
  type: LoadBalancer
  selector:
    app: agent-gke-demo
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
